spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supermarket?useunicode=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

    thymeleaf:
      enabled: true  #开启thymeleaf视图解析
      encoding: utf-8  #编码
      prefix: classpath:/templates/  #前缀
      cache: false  #是否使用缓存
      mode: HTML  #严格的HTML语法模式
      suffix: .html  #后缀名
  #配置静态资源的位置
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
#  mvc:
#    view:
#     prefix: classpath:/templates/
#     suffix: .html


#静态资源访问路径
#    mvc: static-path-pattern=/**
  #静态资源映射路径
#    resources: static-locations=classpath:/


#showSql （设置接口包的日志输出级别为 ：debug。为了打印sql）
logging:
  level:
    com:
      hc:
        chapter04:
          mapper: debug


mybatis:
  mapper-locations: classpath:com/mapper/*.xml

##配置支持thymeleaf模板引擎
#thymeleaf:
#  cache: false
#  prefix: classpath:templates/
#  suffix: .html
